/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClimbsRouteImport } from './routes/climbs'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as ClimbsIdRouteImport } from './routes/climbs.$id'
import { Route as AreasAreaIdRouteImport } from './routes/areas.$areaId'

const ClimbsRoute = ClimbsRouteImport.update({
  id: '/climbs',
  path: '/climbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreasRoute,
} as any)
const ClimbsIdRoute = ClimbsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClimbsRoute,
} as any)
const AreasAreaIdRoute = AreasAreaIdRouteImport.update({
  id: '/$areaId',
  path: '/$areaId',
  getParentRoute: () => AreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/climbs': typeof ClimbsRouteWithChildren
  '/areas/$areaId': typeof AreasAreaIdRoute
  '/climbs/$id': typeof ClimbsIdRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/climbs': typeof ClimbsRouteWithChildren
  '/areas/$areaId': typeof AreasAreaIdRoute
  '/climbs/$id': typeof ClimbsIdRoute
  '/areas': typeof AreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/climbs': typeof ClimbsRouteWithChildren
  '/areas/$areaId': typeof AreasAreaIdRoute
  '/climbs/$id': typeof ClimbsIdRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas'
    | '/climbs'
    | '/areas/$areaId'
    | '/climbs/$id'
    | '/areas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/climbs' | '/areas/$areaId' | '/climbs/$id' | '/areas'
  id:
    | '__root__'
    | '/'
    | '/areas'
    | '/climbs'
    | '/areas/$areaId'
    | '/climbs/$id'
    | '/areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRouteWithChildren
  ClimbsRoute: typeof ClimbsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/climbs': {
      id: '/climbs'
      path: '/climbs'
      fullPath: '/climbs'
      preLoaderRoute: typeof ClimbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof AreasRoute
    }
    '/climbs/$id': {
      id: '/climbs/$id'
      path: '/$id'
      fullPath: '/climbs/$id'
      preLoaderRoute: typeof ClimbsIdRouteImport
      parentRoute: typeof ClimbsRoute
    }
    '/areas/$areaId': {
      id: '/areas/$areaId'
      path: '/$areaId'
      fullPath: '/areas/$areaId'
      preLoaderRoute: typeof AreasAreaIdRouteImport
      parentRoute: typeof AreasRoute
    }
  }
}

interface AreasRouteChildren {
  AreasAreaIdRoute: typeof AreasAreaIdRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasAreaIdRoute: AreasAreaIdRoute,
  AreasIndexRoute: AreasIndexRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

interface ClimbsRouteChildren {
  ClimbsIdRoute: typeof ClimbsIdRoute
}

const ClimbsRouteChildren: ClimbsRouteChildren = {
  ClimbsIdRoute: ClimbsIdRoute,
}

const ClimbsRouteWithChildren =
  ClimbsRoute._addFileChildren(ClimbsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRouteWithChildren,
  ClimbsRoute: ClimbsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
